/* automatically generated by rust-bindgen 0.71.1 */

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _sr_table_t {
    pub value: [u32; 16usize],
    pub sdr1: u32,
}
pub type sr_table_t = _sr_table_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _bat_t {
    pub h: u32,
    pub l: u32,
}
pub type bat_t = _bat_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _bat_table_t {
    pub bat: [bat_t; 8usize],
}
pub type bat_table_t = _bat_table_t;
unsafe extern "C" {
    pub fn KernelReadSRs(table: *mut sr_table_t);
    pub fn KernelWriteSRs(table: *mut sr_table_t);
    pub fn KernelCopyData(dst: u32, src: u32, len: u32);
    pub fn KernelReadPTE(outputAddr: u32, length: i32);
    pub fn KernelWritePTE(inputAddr: u32, length: i32);
    pub fn KernelNOPAtPhysicalAddress(addr: u32);
    pub fn KernelPatchSyscall(index: u32, addr: u32);
}
